# Form implementation generated from reading ui file 'UI\Problems.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Problems(object):
    def setupUi(self, Problems):
        Problems.setObjectName("Problems")
        Problems.resize(1093, 781)
        Problems.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Problems)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Problems)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ignore)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.errors_GroupBox = QtWidgets.QGroupBox(parent=Problems)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errors_GroupBox.sizePolicy().hasHeightForWidth())
        self.errors_GroupBox.setSizePolicy(sizePolicy)
        self.errors_GroupBox.setObjectName("errors_GroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.errors_GroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(parent=self.errors_GroupBox)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.listWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.listWidget.setProperty("showDropIndicator", False)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setProperty("isWrapping", False)
        self.listWidget.setWordWrap(True)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.verticalLayout_2.addWidget(self.errors_GroupBox)
        self.conflicts_GroupBox = QtWidgets.QGroupBox(parent=Problems)
        self.conflicts_GroupBox.setObjectName("conflicts_GroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.conflicts_GroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.treeWidget = QtWidgets.QTreeWidget(parent=self.conflicts_GroupBox)
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.treeWidget.setColumnCount(3)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "Name")
        self.treeWidget.header().setCascadingSectionResizes(False)
        self.treeWidget.header().setDefaultSectionSize(500)
        self.treeWidget.header().setMinimumSectionSize(300)
        self.verticalLayout_3.addWidget(self.treeWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.addButton = QtWidgets.QPushButton(parent=self.conflicts_GroupBox)
        self.addButton.setEnabled(False)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.conflicts_GroupBox)

        self.retranslateUi(Problems)
        self.buttonBox.accepted.connect(Problems.accept) # type: ignore
        self.buttonBox.rejected.connect(Problems.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Problems)

    def retranslateUi(self, Problems):
        _translate = QtCore.QCoreApplication.translate
        Problems.setWindowTitle(_translate("Problems", "BSBB - Build Conflicts"))
        self.errors_GroupBox.setTitle(_translate("Problems", "Errors"))
        self.listWidget.setSortingEnabled(True)
        self.conflicts_GroupBox.setTitle(_translate("Problems", "Conflicts / Ignored Slider Sets"))
        self.treeWidget.headerItem().setText(1, _translate("Problems", "Groups"))
        self.treeWidget.headerItem().setText(2, _translate("Problems", "Source"))
        self.addButton.setToolTip(_translate("Problems", "Adds and checked conflicts above to the top of the build\'s include list.\n"
"NOTE: Recommended to add Groups first to resolve conflicts and only use this for when no unique group for conflict"))
        self.addButton.setText(_translate("Problems", "Add to Builds"))
